/**:
  ros__parameters:
    output_dir: "/aichallenge/record"
    storage_id: mcap
    all_topics: false
    topics:
      - /control/command/control_cmd
      # - /sensing/camera/image_raw
      # - /sensing/camera/camera_info
      # - /sensing/imu/imu_raw
      # - /sensing/gnss/nav_sat_fix
      # - /vehicle/status/steering_status
      - /vehicle/status/velocity_status
      - /localization/pose_with_covariance
      - /sensing/lidar/scan
      - /sensing/lidar/scan_without_obstacles
      - /perception/virtual_scan_bev/image
      - /rsu/curve_01/scan
      - /rsu/curve_02/scan
      - /rsu/curve_03/scan
      - /rsu/curve_04/scan
      - /rsu/curve_05/scan
      - /rsu/curve_06/scan
