rsu_laserscan_generator_node:
  ros__parameters:
    use_sim_time: true
    map_frame_id: map
    enable_v2x_vehicles: true
    v2x_topic: /v2x/vehicle_positions
    v2x_vehicle_radius: 1.0
    v2x_timeout_sec: 1.0
    publish_static_tf: true
    default_fov_deg: 70.0
    default_max_range: 45.0
    default_range_min: 0.05
    default_timer_hz: 20.0
    default_num_rays: 361
    default_hit_rank: 2
    debug: true
    rsu_count: 6
    rsu_id_prefix: curve_

    rsu_ids:
      - curve_01
      - curve_02
      - curve_03
      - curve_04
      - curve_05
      - curve_06

    rsus:
      curve_01:
        frame_id: rsu_curve_01_laser
        topic: /rsu/curve_01/scan
        x: 89620.233296
        y: 43157.347478
        z: 6.500
        yaw_deg: 111.000
        fov_deg: 135.000
        max_range: 15.000
        range_min: 0.050
        num_rays: 361
        hit_rank: 2
        target_boundary: any
      curve_02:
        frame_id: rsu_curve_02_laser
        topic: /rsu/curve_02/scan
        x: 89639.094992
        y: 43147.310706
        z: 6.500
        yaw_deg: -60.000
        fov_deg: 135.000
        max_range: 20.000
        range_min: 0.050
        num_rays: 361
        hit_rank: 2
        target_boundary: any
      curve_03:
        frame_id: rsu_curve_03_laser
        topic: /rsu/curve_03/scan
        x: 89629.923709
        y: 43179.151500
        z: 6.500
        yaw_deg: 110.000
        fov_deg: 150.000
        max_range: 20.000
        range_min: 0.050
        num_rays: 361
        hit_rank: 2
        target_boundary: any
      curve_04:
        frame_id: rsu_curve_04_laser
        topic: /rsu/curve_04/scan
        x: 89655.187999
        y: 43180.362834
        z: 6.500
        yaw_deg: 30.000
        fov_deg: 180.000
        max_range: 15.000
        range_min: 0.050
        num_rays: 361
        hit_rank: 2
        target_boundary: any
      curve_05:
        frame_id: rsu_curve_05_laser
        topic: /rsu/curve_05/scan
        x: 89655.014956
        y: 43167.730346
        z: 6.500
        yaw_deg: -130.000
        fov_deg: 150.000
        max_range: 15.000
        range_min: 0.050
        num_rays: 361
        hit_rank: 2
        target_boundary: any
      curve_06:
        frame_id: rsu_curve_06_laser
        topic: /rsu/curve_06/scan
        x: 89665.916671
        y: 43154.751761
        z: 6.500
        yaw_deg: 5.000
        fov_deg: 150.000
        max_range: 30.000
        range_min: 0.050
        num_rays: 361
        hit_rank: 2
        target_boundary: any
